spring.application.name=FIT_Challenge
#spring.cloud.function.definition=streamLambdaHandler

spring.datasource.url=jdbc:mysql://fitaichallengedb.chy8a8q2a5no.ap-southeast-1.rds.amazonaws.com:3306/fit_challenge
spring.datasource.username=admin
spring.datasource.password=6R2KEAXHtuiRM6kHcCaF
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret = "du-an-safjhdskfjskjliuuasdhaos-2321"
jwt.expiration = 8640000